"""Simulation exports, loaded on demand so pure v2 imports do not initialize GPUs.

Legacy convenience imports remain supported; explicit StageLoader/registry access
also registers the bundled example plugins. Numerical execution loads its backend.
"""

from importlib import import_module
from typing import Any

_EXPORTS = {
    "AVAILABLE_MODES": ("stage_config", "AVAILABLE_MODES"),
    "AutoHybridizationStage": ("stages", "AutoHybridizationStage"),
    "BackgroundManagementStage": ("stages", "BackgroundManagementStage"),
    "BaseStage": ("stages", "BaseStage"),
    "BuildReportStage": ("stages", "BuildReportStage"),
    "DependencyError": ("stages", "DependencyError"),
    "EmbeddingStage": ("stages", "EmbeddingStage"),
    "ExportDataStage": ("stages", "ExportDataStage"),
    "FetchSpeciesStage": ("stages", "FetchSpeciesStage"),
    "FinalMortalityStage": ("stages", "FinalMortalityStage"),
    "FinalizeStage": ("stages", "FinalizeStage"),
    "FoodWebStage": ("stages", "FoodWebStage"),
    "GeneActivationStage": ("stages", "GeneActivationStage"),
    "GeneFlowStage": ("stages", "GeneFlowStage"),
    "GeneticDriftStage": ("stages", "GeneticDriftStage"),
    "InitStage": ("stages", "InitStage"),
    "LegacyTurnRunner": ("legacy_engine", "LegacyTurnRunner"),
    "LogCategory": ("logging_config", "LogCategory"),
    "LogFilter": ("logging_config", "LogFilter"),
    "MapEvolutionStage": ("stages", "MapEvolutionStage"),
    "ModeParameters": ("stage_config", "ModeParameters"),
    "ParsePressuresStage": ("stages", "ParsePressuresStage"),
    "Pipeline": ("pipeline", "Pipeline"),
    "PipelineBuilder": ("pipeline", "PipelineBuilder"),
    "PipelineConfig": ("pipeline", "PipelineConfig"),
    "PipelineMetrics": ("pipeline", "PipelineMetrics"),
    "PipelineResult": ("pipeline", "PipelineResult"),
    "PipelineStageConfig": ("stage_config", "PipelineStageConfig"),
    "PopulationUpdateStage": ("stages", "PopulationUpdateStage"),
    "PostMigrationNicheStage": ("stages", "PostMigrationNicheStage"),
    "PreliminaryMortalityStage": ("stages", "PreliminaryMortalityStage"),
    "PressureTensorStage": ("tensor_stages", "PressureTensorStage"),
    "QuickConsistencyChecker": ("regression_test", "QuickConsistencyChecker"),
    "RegressionResult": ("regression_test", "RegressionResult"),
    "RegressionTestRunner": ("regression_test", "RegressionTestRunner"),
    "SaveHistoryStage": ("stages", "SaveHistoryStage"),
    "SaveMapSnapshotStage": ("stages", "SaveMapSnapshotStage"),
    "SavePopulationSnapshotStage": ("stages", "SavePopulationSnapshotStage"),
    "SimulationContext": ("context", "SimulationContext"),
    "SimulationEngine": ("engine", "SimulationEngine"),
    "SimulationLogManager": ("logging_config", "SimulationLogManager"),
    "SnapshotManager": ("snapshot", "SnapshotManager"),
    "SnapshotMetadata": ("snapshot", "SnapshotMetadata"),
    "SpeciationDataTransferStage": ("stages", "SpeciationDataTransferStage"),
    "SpeciationStage": ("stages", "SpeciationStage"),
    "Stage": ("stages", "Stage"),
    "StageConfig": ("stage_config", "StageConfig"),
    "StageDependency": ("stages", "StageDependency"),
    "StageDependencyValidator": ("stages", "StageDependencyValidator"),
    "StageLoader": ("stage_config", "StageLoader"),
    "StageLogger": ("logging_config", "StageLogger"),
    "StageMetrics": ("pipeline", "StageMetrics"),
    "StageOrder": ("stages", "StageOrder"),
    "StageRegistry": ("stage_config", "StageRegistry"),
    "StageResult": ("stages", "StageResult"),
    "StageSummary": ("logging_config", "StageSummary"),
    "SubspeciesPromotionStage": ("stages", "SubspeciesPromotionStage"),
    "TectonicMovementStage": ("stages", "TectonicMovementStage"),
    "TensorEcologyStage": ("tensor_stages", "TensorEcologyStage"),
    "TensorMetricsStage": ("tensor_stages", "TensorMetricsStage"),
    "TensorStateSyncStage": ("tensor_stages", "TensorStateSyncStage"),
    "TieringAndNicheStage": ("stages", "TieringAndNicheStage"),
    "VegetationCoverStage": ("stages", "VegetationCoverStage"),
    "WorldSnapshot": ("snapshot", "WorldSnapshot"),
    "configure_log_filter": ("logging_config", "configure_log_filter"),
    "create_snapshot": ("snapshot", "create_snapshot"),
    "create_stage_config_from_engine_flags": (
        "stage_config",
        "create_stage_config_from_engine_flags",
    ),
    "disable_debug_logging": ("logging_config", "disable_debug_logging"),
    "enable_debug_logging": ("logging_config", "enable_debug_logging"),
    "generate_regression_report": ("regression_test", "generate_regression_report"),
    "get_default_stages": ("stages", "get_default_stages"),
    "get_log_manager": ("logging_config", "get_log_manager"),
    "get_minimal_tensor_stages": ("tensor_stages", "get_minimal_tensor_stages"),
    "get_mode_description": ("stage_config", "get_mode_description"),
    "get_mode_parameters": ("stage_config", "get_mode_parameters"),
    "get_snapshot_manager": ("snapshot", "get_snapshot_manager"),
    "get_stage_logger": ("logging_config", "get_stage_logger"),
    "get_tensor_stages": ("tensor_stages", "get_tensor_stages"),
    "list_snapshots": ("snapshot", "list_snapshots"),
    "load_mode_with_parameters": ("stage_config", "load_mode_with_parameters"),
    "load_stage_config_from_yaml": ("stage_config", "load_stage_config_from_yaml"),
    "register_stage": ("stage_config", "register_stage"),
    "restore_from_snapshot": ("snapshot", "restore_from_snapshot"),
    "run_quick_consistency_check": ("regression_test", "run_quick_consistency_check"),
    "stage_registry": ("stage_config", "stage_registry"),
}

__all__ = [
    "SimulationEngine",
    "SimulationContext",
    "LegacyTurnRunner",
    "Pipeline",
    "PipelineBuilder",
    "PipelineConfig",
    "PipelineResult",
    "PipelineMetrics",
    "StageMetrics",
    "Stage",
    "BaseStage",
    "StageOrder",
    "StageResult",
    "StageDependency",
    "StageDependencyValidator",
    "DependencyError",
    "get_default_stages",
    "StageConfig",
    "PipelineStageConfig",
    "StageRegistry",
    "stage_registry",
    "register_stage",
    "create_stage_config_from_engine_flags",
    "load_stage_config_from_yaml",
    "get_mode_description",
    "get_mode_parameters",
    "load_mode_with_parameters",
    "ModeParameters",
    "AVAILABLE_MODES",
    "StageLoader",
    "RegressionTestRunner",
    "RegressionResult",
    "QuickConsistencyChecker",
    "generate_regression_report",
    "run_quick_consistency_check",
    "SnapshotManager",
    "WorldSnapshot",
    "SnapshotMetadata",
    "create_snapshot",
    "list_snapshots",
    "restore_from_snapshot",
    "get_snapshot_manager",
    "LogCategory",
    "StageLogger",
    "StageSummary",
    "LogFilter",
    "SimulationLogManager",
    "get_log_manager",
    "get_stage_logger",
    "configure_log_filter",
    "enable_debug_logging",
    "disable_debug_logging",
    "PressureTensorStage",
    "TensorEcologyStage",
    "TensorStateSyncStage",
    "TensorMetricsStage",
    "get_tensor_stages",
    "get_minimal_tensor_stages",
]


def __getattr__(name: str) -> Any:
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute = _EXPORTS[name]
    module = import_module(f".{module_name}", __name__)
    if module_name == "stage_config":
        import_module(".plugin_stages", __name__)
    value = getattr(module, attribute)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_EXPORTS))
